[[snippets]]
  description = "Show expiration date of SSL certificate"
  command = "echo | openssl s_client -connect example.com:443 2>/dev/null |openssl x509 -dates -noout"
  output = ""

[[snippets]]
  description = "List firewall"
  command = "firewall-cmd --list-services --zone=public --permanent"
  output = ""
