[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if dein#util#_is_windows()
        let cmd = 'tools\\update-dll-mingw'
    elseif dein#util#_is_cygwin()
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'gregsexton/MatchTag'

[[plugins]]
repo = 'xolox/vim-session'
depends = ['vim-misc']

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'open-browser.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.vim'
#on_ft = ['markdown']

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'elzr/vim-json'

[[plugins]]
repo = 'thinca/vim-singleton'

[[plugins]]
repo = 'tyru/restart.vim'

[[plugins]]
repo = 'cisco.vim'

[[plugins]]
repo = 'bbchung/gtags.vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'basyura/twibill.vim'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'sgur/unite-everything'
if = '''! has('win32') || has('win64') '''

[[plugins]]
repo = 'Konfekt/FastFold'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'AnsiEsc.vim'

# ColorScheme
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

